server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/qlkh?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: Viethien1@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: this-is-my-ultra-long-jwt-secret-key-Viethien1@7890
  expiration-ms: 86400000


file:
  upload-dir: uploads        # thư mục gốc trong project



eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
